spring.application.name=ingestion-service


# System Server Configuration
server.port=8080

# Spring Kafka Properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# Spring Kafka Consumer Properties
spring.kafka.consumer.group-id=samsung-analytics-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Switch Kafka acknowledgment mode to MANUAL
spring.kafka.listener.ack-mode=manual

# Spring Data R2DBC Database Properties
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/iot_analytics
spring.r2dbc.username=samsung_admin
spring.r2dbc.password=samsung_secure_pass
